PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS Qrcode;
CREATE TABLE Qrcode (
    qr_ID INTEGER PRIMARY KEY NOT NULL,
    qrcode BLOB UNIQUE NOT NULL
);

DROP TABLE IF EXISTS Piece;
CREATE TABLE Piece (
    piece_ID INTEGER PRIMARY KEY NOT NULL,

    qrcode

    FOREIGN KEY (qrcode) REFERENCES Qrcode(qr_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
